# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2021-2026 Axiado Corporation (or its affiliates).

obj-y	:=	scm3005.o ax_devcfg.o

# Build the parser with -fshort-enums
CFLAGS_ax_devcfg.o	+= -fshort-enums
